name: CI

on: push

jobs:
  lingting:
    runs-on: ubuntu-latest

    steps:
    - name: code checkout(push code to github)
      uses: actions/checkoutv3

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: upgrated pip
      run: |
        pip install --upgrade pip

    - name: install flake8
      run: |
        pip install flake8

    - name: run flake8
      run: |
        flake8 app.py
