name: CI

on: 
  push: # Trigger the workflow on every push event

jobs:
  linting: # Define a job named 'linting'
    runs-on: ${{ matrix.os }} # Specify the operating system for the job

  strategy:
    matrix:
      os: [ubuntu-latest,macos-latest,windows-latest]
      version: ['3.9','3.10']

    steps:
    - name: Checkout code # Step to checkout the code from the repository
      uses: actions/checkout@v3

    - name: Set up Python # Step to set up the Python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.version}} # Specify Python version

    - name: Upgrade pip # Step to upgrade pip to the latest version
      run: |
        python -m pip install --upgrade pip

    - name: Install Flake8 # Step to install the Flake8 linting tool
      run: |
        pip install flake8

    - name: Run Flake8 # Step to run Flake8 linting on 'app.py'
      run: |
        flake8 app.py
